### ISSUE TITLE
Weighting alternatives for an experiment

### ISSUE THREAD

**Issue by inkredabull** [assaf/vanity#179]
Hello, I've gone through docs, issues, and pull-requests and don't find mention of an ability to weight `alternatives`. The Use Case is to assign a higher percentage probability of assignment (e.g. 96%) to a 'control' variation to ensure that most users continue having the default experience while assigning lower probabilities to test variations (e.g. 2 variations each at 2%.) 

From what I've been able to gather, for n variations, Vanity will assign each of those with a probability of 1/n.  Would be great if each of the variations could be given a weight. Thank you.

**Comment by dunkstewart** [comment]
Another way to do it that worked for me is:

```ruby
ab_test :donation_forms_multistep_remains_best do
  description "Run multistep but direct 5% of traffic to conventional"
  alternatives :conventional, :multi_step
  metrics :money
  
  alternatives.tap do |as|
    as[0].probability = 5
    as[1].probability = 95
    set_alternative_probabilities as
  end
end
```

**Comment by phillbaker** [comment]
@dunkstewart that's great! I'll add that to the docs as a workaround until something more permanent is built.
