### ISSUE TITLE
jQuery errors

### ISSUE THREAD

**Issue by excid3** [assaf/vanity#237]
I have been getting a bunch of jQuery errors on the Vanity dashboard because I'm using a newer version of jQuery that the one this ships with. I didn't realize it until looking through the gem and realizing it looks like the dashboard is designed to render without the Rails app's application layout. All my Javascript was trying to execute against an incompatible version of jQuery throwing a bunch of errors on this page.

There are 2 good options here: 
1. Just update this line to `render layout: false` so we don't inherit any of the stuff from the main Rails app
https://github.com/assaf/vanity/blob/master/lib/vanity/frameworks/rails.rb#L290
2. Migrate to using jquery-rails and the asset pipeline for everything. If you go this route, you probably want the vanity rails dashboard not to include the whole html document and render just the div content instead.

I can see it going both ways. Option 1 is the much simpler approach I think. I'm curious what your thoughts are on this?

Btw, love Vanity. :+1:

**Comment by phillbaker** [comment]
@excid3 closing as per the comment above, please re-open if there are further issues.
