### ISSUE TITLE
Need a donate button.

### ISSUE THREAD

**Issue by dsignr** [assaf/vanity#238]
Hi, thanks for your hard work - In the raile ecosystem, good A/B testing frameworks are pretty rare (but you know this already). It would be nice to have a donate button somewhere so people can donate to this project so they can show their way of supporting the project :) 

Thank you so much for this gem, using this in production!

**Comment by phillbaker** [comment]
For now i'll include a link here for my personal Gratipay (was gittip) in case folks come looking:  [![gratipay - phillbaker](https://img.shields.io/gratipay/phillbaker.svg)](https://gratipay.com/phillbaker/)

if we get more folks working on this project, I'll move it to the readme and create a team for it.
