### ISSUE TITLE
Vanity failing to access database on Heroku

### ISSUE THREAD

**Issue by raphaelpflieger** [assaf/vanity#251]
Hey there,

Thanks for your work on this incredibly useful gem. I've played with it a lot on my localhost, but it failed to work while on production on Heroku. I get the following error while trying to access the main report page:

`ActionView::Template::Error (could not translate host name "ec2-XX-XXX-XXX-XXX.eu-west-1.compute.amazonaws.com:5642" to address: Name or service not known )`

(XXs in ec2 path were added by me)

Here is the rest of the logs:

    6:       Vanity.metric("#{vanity_h(id)}")
    7:         .plot([{
    8:           label:"#{vanity_h(metric.name)}",
    9:           data: [#{Vanity::Metric.data(metric).map { |date,value| "['#{date.to_time.httpdate}',#{value}]" }.join(",")}]
    10:         }])
    11:     })
    12:     </script>}
    app/views/vanity/_metric.erb:9:in `_app_views_vanity__metric_erb__400322292071622517_70194567122580'
    app/views/vanity/_metrics.erb:4:in `block in _app_views_vanity__metrics_erb__533107748726636358_70194566826760'
    app/views/vanity/_metrics.erb:2:in `each'
    app/views/vanity/_metrics.erb:2:in `_app_views_vanity__metrics_erb__533107748726636358_70194566826760'
    app/views/vanity/_report.erb:49:in `_app_views_vanity__report_erb___4325486560256375919_70194565783140'

**Comment by phillbaker** [comment]
Thanks for using vanity! Can you post an (annonymized) version of your
`config/vanity.yml` ?

**Comment by phillbaker** [comment]
Also, as a reference, here's a repo of vanity running in rails on Heroku: https://github.com/phillbaker/vanity-rails3-demo, available at http://vanity-rails3-demo.herokuapp.com, and [visit the dashboard](http://vanity-rails3-demo.herokuapp.com/vanity).

**Comment by raphaelpflieger** [comment]
Sure, here's the part used in production (and thank you so much for reacting so quickly):

    adapter: active_record
    active_record_adapter: postgresql
    <% unless ENV['DATABASE_URL'].nil? %>
    <% username, password, host, database = ENV['DATABASE_URL'].scan(%r{//(.*):(.*)@(.*)/(.*)}).first %>
    host:     <%= host %>
    username: <%= username %>
    password: <%= password %>
    database: <%= database %>
    <% end %>
    pool: 5

This configuration came from this blog post : http://www.jonathankirst.com/2012/06/rails-ab-testing-with-vanity.html

What is kinda weird is that if I use metrics based on ActiveRecord models everything works fine. This error is only throwed when trying to call metrics recorded with the track! method...

I must add I'm using Postgis, do you think it has any impact on this ?

**Comment by phillbaker** [comment]
@raphaelpflieger two thoughts: 
* as the error says, you're not separate the host from the port: "ec2-XX-XXX-XXX-XXX.eu-west-1.compute.amazonaws.com:5642" has the port appended to it, I think you'll need to separate that into a port attribute
* if you want to re-use the existing ActiveRecord connection and avoid the duplicate between database.yml and vanity.yml, you could use a config like:
```
adapter: active_record
active_record_adapter: default
```

**Comment by raphaelpflieger** [comment]
Using `active_record_adapter: default` and removing `Vanity.playground.establish_connection` from the `after_fork` block in the unicorn server config file did the trick, everything is working smoothly now. Thanks again for your help !
