### ISSUE TITLE
Dashboard Missing template

### ISSUE THREAD

**Issue by daniel-nelson** [assaf/vanity#252]
I've followed the instructions in https://github.com/assaf/vanity/tree/2-0-stable#step-5-check-the-report for installing the dashboard, but when I hit http://localhost:5000/vanity, it throws the following:

  Missing template ...app/views/vanity/_report with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :arb, :haml]}. Searched in:
    * "...app/views"
    * "....rvm/gems/ruby-2.1.5/gems/jasmine-rails-0.10.7/app/views"
    * "....rvm/gems/ruby-2.1.5/gems/letter_opener_web-1.2.3/app/views"

Vanity 2.0.0.beta5
Rails 4.2.1

**Comment by phillbaker** [comment]
@daniel-nelson thanks for the report, just curious I see jasmine in the stacktrace, are you hitting this error during testing?

**Comment by daniel-nelson** [comment]
@phillbaker, no, in development. Jasmine Rails exposes a /specs route in development where we can run our Jasmine specs by visiting the page in a browser.

**Comment by daniel-nelson** [comment]
Running vanity from the command line also throws an error about a missing template:
$ vanity report --output vanity.html
.../.rvm/gems/ruby-2.1.5/bundler/gems/vanity-72459d7dbd6e/lib/vanity/commands/report.rb:59:in `read': No such file or directory @ rb_sysopen - .../app/views/vanity/_report.erb (Errno::ENOENT)

Strange thing is that someone else on my team can run from the command line in this same project with no problems.

**Comment by aprilw** [comment]
I'm also encountering both of these problems (using Ruby 2.1.0).

**Comment by aprilw** [comment]
One other note: when I installed the gem version, the report page generated mostly fine, though there was an error shown in red in the metrics portion (1 argument for 0).  However, when I switched to the latest version of master, that's when I started encountering the above problems.

**Comment by phillbaker** [comment]
So I think the problem is that the README instructions create an empty `app/views/vanity` directory, if you remove that directory, you should stop seeing this error. I'm also working on a code fix.

**Comment by aprilw** [comment]
Thank you, @phillbaker!
