### ISSUE TITLE
How can I integrate vanity in another controller?

### ISSUE THREAD

**Issue by rept** [assaf/vanity#255]
I already have an admin controller which uses it's own security to allow looking at exit surveys and visitors of website.  Would it be possible to integrate vanity into that?

So I could create a method there which would render the vanity dashboard?

**Comment by phillbaker** [comment]
@rept definitely possible, you should just `include Vanity::Rails::Dashboard` in the controller you're using. The routes suggested in the readme,
```
get '/vanity' =>'vanity#index'
get '/vanity/participant/:id' => 'vanity#participant'
post '/vanity/complete'
post '/vanity/chooses'
post '/vanity/reset'
```
would also have to be updated to match the new controller.

**Comment by rept** [comment]
Thanks for your speedy reply.

I altered the routes like this:

     constraints :subdomain => 'admin' do
       get '/' => 'admin#index'
       get '/vanity' =>'admin#vanity'
       get '/vanity/participant/:id' => 'admin#participant'
     end

The routes are ok I think, but what's not clear, is how to tell the controller to render the view.

This is the controller:

    class AdminController < ApplicationController
      include Vanity::Rails::Dashboard
      layout 'layouts/admin'
      skip_before_filter :authorize

      def index
        @users = User.where(:role_id => [0,1]).order('last_sign_in_at desc')
      end
  
      def vanity
        ### What needs to go here? ###
      end

**Comment by phillbaker** [comment]
That module defines the routes, so by including it, there's no need to
define methods explicitly. If you define methods like #index, that will
override the included Vanity index.

**Comment by rept** [comment]
Ok that's clear, thanks.
