### ISSUE TITLE
Bug in ab_test.rb track! method

### ISSUE THREAD

**Issue by srklonaris** [assaf/vanity#258]
When you pass an identity to the track! method it doesn't override the identity() method that is being used to get the identity.

identity = identity() rescue nil
identity ||= args.last[:identity] if args.last.is_a?(Hash) && args.last[:identity]

||= identity fails because identity is not nil but it should still set the value to args.last[:identity]

**Comment by phillbaker** [comment]
@srklonaris thanks for reporting this bug, we'll get this fixed up shortly.
