### ISSUE TITLE
Mongoid Support

### ISSUE THREAD

**Issue by ethangunderson** [assaf/vanity#26]
We'd like to use Vanity metrics with our project using Mongoid. After a bit of looking, it doesn't look like there is any support for it. Is anyone working on this? Would it just be another class under metrics that follows the same api as the Active Record one?

**Comment by phillbaker** [comment]
With the release of the merged mongo driver (https://www.mongodb.com/blog/post/announcing-ruby-driver-20-rewrite), I think the goal should be to move to update the existing mongo driver and skip supporting mongoid. Hard to believe this has been open for 5 years.
