### ISSUE TITLE
Using vanity with CDNs

### ISSUE THREAD

**Issue by antgel** [assaf/vanity#264]
Hi,

I'm asking here as I didn't manage to find alternative discussion groups or support channels for vanity.  We're looking to revamp our approach to A/B testing, and we are concerned that our use of a CDN can result in caching tests, and our origin not getting the relevant data.  There's a lot to learn in the area, and we're getting there slowly, but for now, we have one basic question - does vanity play well with CDNs?

I hope the question is sensible enough, please let me know if I can clarify it / make it sensible.

Antony

**Comment by phillbaker** [comment]
@antgel it depends on what exactly you're caching - are you caching the entire rendered page? Is there a per-user cache or are pages cached globally?

**Comment by phillbaker** [comment]
@antgel going to close this for now, but thought I'd leave some note for folks who find this.

Assuming that you're using a CDN to cache entire rendered pages that don't require authentication to view (ie they're publicly viewable and experiment alternatives are calculated using cookies not user ids), that you can program rules into your CDN ([like varnish's VCL](https://www.fastly.com/blog/best-practices-for-using-the-vary-header)), and there's only one experiment on a page, the different situations to handle include:
 * when a visitor hasn't been assigned to an experiment they won't have a `vanity_id` cookie, so let the visitor pass through the CDN to be assigned to alternative and have the `vanity_id` cookie set. Vanity doesn't store the chosen alternatives in a cookie by default, but writing an after filter to set a cookie probably would be an easy way to store a cache key for later use. The cache key should include each experiment a user could see, see below for a possible key calculation method. The resulting page should be cached (a header probably needs to be set).
 * if the visitor has a `vanity_id` and a vanity cache key cookie, then we need to retrieve the cache key of the page to show them. 

Possible cache key method:
```ruby
def page_cache_key(vanity_id)
  info = Vanity.playground.participant_info(vanity_identity).map do |info_arr|
    expr = info_arr.first
    alt = info_arr.last
    #{expr.name}=#{expr.fingerprint(alt)
  end
  info.join('&')
end
```
