### ISSUE TITLE
Vanity identification using blocks does not fall back to use cookies

### ISSUE THREAD

**Issue by phantomwhale** [assaf/vanity#268]
I am using v2.0.0beta8 

I have been following the vanity identity guide at http://vanity.labnotes.org/identity.html at it suggest that:

> If you use either block or method name and they return nil, Vanity will fallback on persistent cookie mechanism.

My issue is that I cannot get the persistent cookies mechanism to kick in. I present below what I have tried, and why I believe this may need some code changes to vanity to fix the issue.

In our rails application, the `current_user` method currently returns either a logged in user (with `id` method) or a `NullUser` object, which returns it's `id` as `nil`.

This means a simple `use_vanity :current_user` line in our application_controller does not work for logged out users, as the `current_user` method has a non-null return, but this in turn causes the `@vanity_identity` to be set as nil (the result of our `NullUser#id` method) - see: https://github.com/assaf/vanity/blob/v2.0.0.beta8/lib/vanity/frameworks/rails.rb#L65-L66

I am not sure if that part would be regarded as a bug or not, but in any case I decided to fall back to the more explicit block mechanism, which - as quoted above - should fallback to use cookies whenever the block returns `nil`. But it does not, it simply returns nil for the `vanity_identity` method as well - see: https://github.com/assaf/vanity/blob/v2.0.0.beta8/lib/vanity/frameworks/rails.rb#L48-L49

Either approach therefore causes the following line to trigger, causing a stack trace to be thrown: https://github.com/assaf/vanity/blob/v2.0.0.beta8/lib/vanity/experiment/base.rb#L171

Overriding the NullUser's id method to return `0` allows everything to run, but then all non-logged in users are being treated as the same user, so this does not fix my issue.

Happy to submit a PR to fix this up, if it can be agreed that these chunks of code are not behaving as the documentation suggests they should ?

**Comment by phillbaker** [comment]
Thanks for opening an issue. Yes, this does seem like a couple of bugs. I
think the docs are wrong, there's no fallback mechanism for the block form
at all currently.

A PR that either extracts the fallback behavior and updates the code to use
it if the block returns nil, or that checks that the value of the object.id
call would be great!

Thanks Ben!
