### ISSUE TITLE
Can I create experiments programmatically via a database table?

### ISSUE THREAD

**Issue by jasonfb** [assaf/vanity#269]
I need two distinct kinds of experiments: (1) UX changes that requires a Rails/Javascript developer, and (2) changes of Images and copy which require simply a switch in my custom-built CMS

Vanity works well for #1, but for #2 I want the admin users of my site to be able to create experiments without involving a Rails/Javascript dev and without deploying code.

But unfortunately I see that Vanity basically expects its experiments to be defined in Ruby and inits them when the app boots, so maybe this is a bad idea?

is it possible to do what I'm trying to achieve or is Vanity perhaps the wrong tool ?

**Comment by phillbaker** [comment]
Jason, (2) is something Vanity doesn't currently support, but I'd
definitely like to support it.

If you'd like to play around with a solution and submit a PR that'd be
amazing!

**Comment by jasonfb** [comment]
OK awesome. I will try to give this some thought. is it ok if I ping you over email -- I might some code design questions when I get started.

Will close this issue in the meantime
