### ISSUE TITLE
"warning: circular argument reference - score" in 1.9.2

### ISSUE THREAD

**Issue by lostphilosopher** [assaf/vanity#273]
I bundle installed `gem 'vanity', '1.9.2'` configured for Postgres, and tried to `run rake db:migrate`. Got the following error:  

    $ rake db:migrate
    .../.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/vanity-1.9.2/lib/vanity/experiment/ab_test.rb:305: warning: circular argument reference - score

Line in question: `def conclusion(score = score)`. I started looking into forking, but I see the master branch has [`def conclusion(score = score())`](https://github.com/assaf/vanity/blob/master/lib/vanity/experiment/ab_test.rb#L296) so this might be in flux. What's the right way to proceed? 

Completely possible I just Postgres config-ed wrong and this is all a red herring, but figured I'd check with the experts.

**Comment by phillbaker** [comment]
Hm, if there was a specific patch that fixed it, let's cherry pick it back
to the 1.9.2 branch - a PR would be great!
