### ISSUE TITLE
Multiple experiments

### ISSUE THREAD

**Issue by billybonks** [assaf/vanity#280]
Can you run multiple experiments at different locations using vanity. i am concerned about session cookies and such.

**Comment by phillbaker** [comment]
@billybonks Vanity does support multiple experiments at the same time. Were you having an issue with a specific case?

**Comment by billybonks** [comment]
no i wasn't having an issue, i just couldn't find anything in the documentation. does vanity create a session token for every experiment ?

**Comment by phillbaker** [comment]
@billybonks yes, Vanity does support multiple experiments. The examples in the readme are a good starting spot. Vanity creates a single `vanity_id` cookie by default which is used to identify participants across different experiments.

**Comment by billybonks** [comment]
thanks
