### ISSUE TITLE
Infinite loop when starting app without Redis running

### ISSUE THREAD

**Issue by danhunter** [assaf/vanity#292]
Seems to be an issue with Vanity 2.1.0, Rails 4.2. When attempting to start the rails server and either the REDIS_URL env variable is not defined or the server is not running, it gets stuck in a loop of `No default alternative specified;`

To replicate: 
Setup a new app, add devise, redis, redis-namespace, and vanity to gemfile. 
Setup devise, run migrations. 
Setup vanity to connect to localhost Redis via REDIS_URL environment variable. 
Create experiment.
Ensure Redis is not running locally.
Attempt to start rails server.

Notes: 

Vanity handles Redis going down while the server is running perfectly fine, its only a problem when attempting to start the server without Redis running.

Setting a default has no effect other than removing the warning message. App still fails to start.

**Comment by phillbaker** [comment]
@danhunter thanks for the bug report. 

This looks tied to https://github.com/assaf/vanity/pull/281 and its introduction of an experiment default. I'll take a look and see if there's an easy fix.
