### ISSUE TITLE
View results in http://www.abtestcalculator.com

### ISSUE THREAD

**Issue by askehansen** [assaf/vanity#293]
Could there be a link to http://www.abtestcalculator.com for each experiment?
I'd be happy to create the pull request if that would be accepted

**Comment by phillbaker** [comment]
@askehansen thanks for opening an issue! Is there a way we could make the link relevant to each experiment? Maybe we could pre-fil some values on the page via url parameters?

**Comment by askehansen** [comment]
Yep thats the idea.
I made a branch for this but right now its kinda messy: https://github.com/assaf/vanity/compare/master...askehansen:ab-calculator

I'd also like it to compare the original with the best alternative if there are more than 2

**Comment by phillbaker** [comment]
@askehansen if you'd like to submit a PR, that'd be best - it's much easier to review code! For now, I'll close this issue as the original question has been answered.
