### ISSUE TITLE
Dashboard missing translation

### ISSUE THREAD

**Issue by pawlarius** [assaf/vanity#329]
Just wondering, do we need to manually input the translation or this is an error?
![screen shot 2017-08-05 at 2 15 36 pm](https://user-images.githubusercontent.com/27823957/28993766-ae1735aa-79e8-11e7-9cae-84a6520ae3c0.png)

**Comment by phillbaker** [comment]
Thanks for opening an issue and the screenshot - definitely looks like a bug

**Comment by Pawlarius** [comment]
if i press the reset button it clears the experiment, but how to clear the current number in the chart? @phillbaker

**Comment by phillbaker** [comment]
@Pawlarius I'm not sure I follow, but that seems like a separate question. Perhaps related to https://github.com/assaf/vanity/issues/200?
