### ISSUE TITLE
Use method ab_test in model

### ISSUE THREAD

**Issue by edenisn** [assaf/vanity#337]
Can we use ```ab_test``` method in model or may be in service class (RoR)?

**Comment by phillbaker** [comment]
Is https://github.com/assaf/vanity#other and https://github.com/assaf/vanity#present-the-different-options-to-your-users what you're looking for?

https://github.com/assaf/vanity/issues/331 may also have more context.

**Comment by edenisn** [comment]
Yep. Thanks @phillbaker
