### ISSUE TITLE
Getting an error from vanity when trying to update redis

### ISSUE THREAD

**Issue by toddmetheny** [assaf/vanity#347]
We just updated our redis instance.

Now we're getting an error any place we have a call to vanity.

For example: 

```setTimeout(function(){
      mixpanel.track('Acquisition Event', {
        'Trigger Type': '8 seconds',
        'Show New Version': <%= ab_test(:sg_20170624_homepage_redesign) %>,
        'Page': 'Homepage'
      })
    }, 8000); // 8 seconds```

The error points to the ab_test line and reads as: 

```>> ab_test(:sg_20170624_homepage_redesign)
!! #<Redis::CommandError: ERR unknown command '[]'>```

**Comment by phillbaker** [comment]
Hey! f06d90b5bddb2c91df44a79d6c3070c57080e7da on master should fix the issue. Haven't done a release yet, but if you could use master for a bit, that's probably the quickest fix.

**Comment by phillbaker** [comment]
@toddmetheny did master fix the issue?

**Comment by toddmetheny** [comment]
@phillbaker Ah---I missed that comment. We switched to use split instead. Wish I had seen it.
