### ISSUE TITLE
Rails 5 Support 

### ISSUE THREAD

**Issue by tansaku** [assaf/vanity#348]
Working with Rails 5 we get the following issue:

```
Directly inheriting from ActiveRecord::Migration is not supported 
```

**Comment by phillbaker** [comment]
Is this a deprecation warning or an error?

This would be good to fix however.

**Comment by tansaku** [comment]
hi @phillbaker it was a blocking error I think

**Comment by phillbaker** [comment]
Looks like https://github.com/RolifyCommunity/rolify/pull/463/files is a good approach.

**Comment by phillbaker** [comment]
Fixed in https://github.com/assaf/vanity/commit/b20d7336c80a75c48abef12caff2526d46554f56
